[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect API calls to backend
[[redirects]]
  from = "/api/*"
  to = "https://landhubproject.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[secrets]
  omit_keys = ["VITE_API_URL", "VITE_SUPABASE_ANON_KEY", "VITE_SUPABASE_URL"]
  omit_paths = ["dist/assets/*.js", "dist/assets/*.css"]